### ISSUE TITLE
solver error

### ISSUE THREAD

**Issue by ktehranchi** [pencleanenergy/MATCH-model#73]
I am running into this error with detecting CBC as a solver...

```
Model created in 0.04 s.
Loading inputs...
Data read in 1.76 s.

Instance created from data in 14.18 s.

Total time spent constructing model: 15.94 s.

ERROR: Unknown IO type: nan
Traceback (most recent call last):
  File "/Users/kamrantehranchi/mambaforge/envs/match_model/bin/match", line 33, in <module>
    sys.exit(load_entry_point('match-model', 'console_scripts', 'match')())
  File "/Users/kamrantehranchi/Local_Documents/MATCH-model/match_model/main.py", line 38, in main
    main()
  File "/Users/kamrantehranchi/Local_Documents/MATCH-model/match_model/solve_scenarios.py", line 169, in main
    solve.main(args=args)
  File "/Users/kamrantehranchi/Local_Documents/MATCH-model/match_model/solve.py", line 171, in main
    results = solve(instance)
  File "/Users/kamrantehranchi/Local_Documents/MATCH-model/match_model/solve.py", line 852, in solve
    if model.options.solver_options_string and not hasattr(
  File "/Users/kamrantehranchi/mambaforge/envs/match_model/lib/python3.10/site-packages/pyomo/opt/base/solvers.py", line 119, in __getattr__
    self._solver_error(attr)
  File "/Users/kamrantehranchi/mambaforge/envs/match_model/lib/python3.10/site-packages/pyomo/opt/base/solvers.py", line 122, in _solver_error
    raise RuntimeError("""Attempting to use an unavailable solver.
RuntimeError: Attempting to use an unavailable solver.

The SolverFactory was unable to create the solver "cbc"
and returned an UnknownSolver object.  This error is raised at the point
where the UnknownSolver object was used as if it were valid (by calling
method "_options_string_to_dict").

The original solver was created with the following parameters:
	solver_io: nan
	type: cbc
	_args: ()
	options: {}

```

**Comment by jsloan-rcea** [comment]
I just ran into the same.
